generators/entity-server/files.js
generators/entity-server/index.js
generators/entity-server/templates/dotnetcore/src/Project/Controllers/EntityController.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Data/ApplicationDatabaseContext.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Data/Extensions/DbContextExtensions.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Data/Extensions/DbSetExtensions.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Data/Extensions/PropertyAccessorCache.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Models/Entity.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Models/Interfaces/IJoinedEntity.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Models/JoinEntity.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Models/RelationshipTools/JoinListFacade.cs.ejs
generators/entity/index.js
generators/server/files.js
generators/server/index.js

Add these 3 lines to ".yo-rc.json" file to make entity generation available : 
"databaseType": "sql",
"devDatabaseType": "h2Memory",
"prodDatabaseType": "mysql"

Contribution

---

generators/entity-server/files.js
generators/entity-server/templates/dotnetcore/src/Project/Controllers/EntityController.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Data/ApplicationDatabaseContext.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Models/Entity.cs.ejs
generators/entity-server/templates/dotnetcore/test/Project.Test/Controllers/EntityResourceIntTest.cs.ejs
generators/entity/index.js
generators/generator-dotnetcore-constants.js
generators/server/files.js

Contribution2

---

generators/client/index.js
generators/entity-client/files.js
generators/entity-client/index.js
generators/entity/index.js
generators/languages/index.js

Generation path of client entities is now corresponding to the .Net C# file tree and client needles paths have been changed
Closes #11

generation path of client entities updated

---

generators/server/index.js
generators/server/prompts.js

Waiting to support multiple databases, fix of "no database configured" error by adding a default database configuration

adding a default database configuration

---

.travis.yml

Related to https://github.com/jhipster/generator-jhipster/pull/10173

Update Node version to 10.16.1

---

generators/languages/index.js

Fixed translation support bug. The problems were a typo in the path of a needle and a missing needle.
Closes #14

Translation support bug fixed

---

package.json

Adding a needed dependancy causing the crash of the blueprint

---

.travis.yml

Related to https://github.com/jhipster/generator-jhipster/pull/10236

Update Node version to 10.16.3

---

.travis.yml

Related to https://github.com/jhipster/generator-jhipster/pull/10707

update Node version to v12.13.0

---

.eslintrc.json

This reduces about 70% of the eslint errors

Fixed eslint complaints on switch/case code blocks

---

.travis.yml

Related with https://github.com/jhipster/generator-jhipster/pull/11067

Update node to version 12.14.0 LTS

---

generators/server/templates/dotnetcore/src/Project/Infrastructure/MvcStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Infrastructure/SecurityStartup.cs.ejs

fix CRUD operation error

---

generators/server/templates/dotnetcore/src/JHipsterNet/JHipsterNet.csproj.ejs
generators/server/templates/dotnetcore/src/Project/Infrastructure/DatabaseStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Infrastructure/MvcStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project/Startup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Web/Rest/Problems/ProblemDetailsConfiguration.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Setup/NhipsterWebApplicationFactory.cs.ejs

- Update to dotnet core 3.1
- Update to latest Nuget packages
- Remove obsolete interface IHostingEnvironment
Related issue #43

update to dotnet core 3.1 version

---

generators/common/templates/dotnetcore/src/Project/Dockerfile.ejs

update Dockerfile - dotnet core 3.1

---

generators/server/templates/dotnetcore/src/Project/Program.cs.ejs

fix build error - remove CertificateFileProvider

---

.travis.yml
package.json

update to generator-jhipster v6.8.0

update to generator-jhipster v6.8.0

---

generators/client/index.js

Fix client build error due to https://github.com/jhipster/generator-jhipster/commit/f3b85715e68e048019bf77841cb49c9a320988e1#diff-b7140d3ad70fccdf93b0e852a5bab27f

Fix client build error 

---

generators/client/index.js

Fix error on client generation when npm install is running

---

.gitignore
.vscode/launch.json
CONTRIBUTING.md
test-integration/samples/app-sample-dev/.yo-rc.json

Added vs code debug

---

package-lock.json
package.json

Bumped the JCore dependency to v7.2.0

---

README.md

Add SonarCloud Badge

---

generators/client/index.js

Fix npm install

---

generators/entity-client/index.js
generators/entity-server/templates/dotnetcore/src/Project/Models/Entity.cs.ejs
generators/server/index.js
package-lock.json

Fix entity generation for one to one relation

---

generators/server/templates/dotnetcore/src/JHipsterNet/Pagination/Extensions/IQueryableExtensions.cs.ejs

Pagination: fix total count

---

.github/workflows/test-integration-jwt.yml
test-integration/scripts/07-run-sonar-analyze.sh

Added sonar analysis on generated app

---

generators/server/files.js
generators/server/templates/dotnetcore/SonarAnalysis.ps1.ejs
generators/server/templates/dotnetcore/SonarQube.Analysis.xml.ejs
generators/server/templates/dotnetcore/src/JHipsterNet/Pagination/Sort.cs.ejs
generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs
test-integration/scripts/03-install-dependencies-app-sample.sh

Exclude generated files in sonar analysis 

---

.github/workflows/generator.yml

Remove manual sonar analysis in fovour of auto analysis

---

README.md

Added "what we have now" section

---

generators/server/templates/dotnetcore/src/Project/Infrastructure/MvcStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs

Add SPA support

---

generators/client/files-common.js

Fix due to #189

---

generators/client/files-common.js
package-lock.json
package.json

Bump dependencies and fix angular generation on windows 

---

.vscode/launch.json
package-lock.json
package.json

Update dependencies ( Jhispter to 6.9.0 ) 

---

generators/server/templates/dotnetcore/src/Project/Controllers/AuthController.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Controllers/AccountControllerTest.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Controllers/ProfileInfoControllerIntTest.cs.ejs

Fix project namespace

---

generators/common/templates/dotnetcore/README.md.ejs
generators/entity-server/files.js
generators/entity-server/templates/dotnetcore/src/Project/Models/JoinEntity.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/AuthController.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/UserController.cs.ejs
generators/server/templates/dotnetcore/src/Project/Service/UserService.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Controllers/AccountControllerTest.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Controllers/ProfileInfoControllerIntTest.cs.ejs

Fix GetAllUsers security

---

.github/workflows/test-integration-jwt.yml
test-integration/scripts/04-generate-entities-sample.sh

Fix sonar analysis on generated entities

---

generators/entity-server/templates/dotnetcore/test/Project.Test/Controllers/EntityResourceIntTest.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/AccountController.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/UserController.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Controllers/AccountResourceIntTest.cs.ejs

Add [Authorize] to secure Account and User controller endpoints

Add [Authorize] to secure Account and User controller endpoints

---

README.md
generators/common/templates/dotnetcore/README.md.ejs
generators/server/templates/dotnetcore/SonarAnalysis.ps1.ejs

SonarQube: fix config file not found

---

generators/entity-server/files.js
generators/entity-server/templates/dotnetcore/src/Project/Models/JoinEntity.cs.ejs
test-integration/samples/jdl-default/app.jdl

Fix multiple many-to-many relationships in JDL

---

generators/common/templates/dotnetcore/src/Project/Dockerfile.ejs

Follow recommendations on Dockerfile, add comments and reduce
final image size by half using aspnet alpine docker image.
Fix jhipster#38

Update the Docker build

---

.gitattributes

Issue #266 
I just updated the file to add .cs to text and the .ejs comprehension for each type of file we might use

Add .cs and precision about language used for ejs

---

generators/server/templates/dotnetcore/src/JHipsterNet/JHipsterNet.csproj.ejs
generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project/Web/Rest/Problems/ProblemDetailsConfiguration.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Project.Test.csproj.ejs

NuGet Package Update for *.csproj
Fix #262 
All Nuget Packages have been updated to latest Release except for the **Hellang.Middleware.ProblemDetails who's still in 2.2.1**
(v5.0 has issues with: 
- options.OnBeforeWriteDetails (Not Enough Informations given for the new version)
- ExceptionProblemDetails() used in __namespace__.Web.Rest.Problems (Another fct has replaced it)
)
✅ Generation + Test with Oracle Database
✅ Generation + Test with SqlLite Database
✅ Generation + Test with PostGres Database
✅ Generation + Test with MySQL Database
✅ Generation + Test with JWT Authentication
✅ Generation + Test with OATH Authentication

NuGet Package Update for *.csproj

---

generators/entity-server/templates/dotnetcore/src/Project/Models/Enum.cs.ejs

Fixes bad identation on enum.
Fix #287

Fix enum identation

---

generators/server/templates/dotnetcore/src/Project/Controllers/AccountController.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/Dto/ProfileInfoDTO.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/ProfileInfoController.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/UserController.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/UserJwtController.cs.ejs
generators/server/templates/dotnetcore/src/Project/Models/Vm/KeyAndPasswordVM.cs.ejs
generators/server/templates/dotnetcore/src/Project/Models/Vm/LoginVM.cs.ejs
generators/server/templates/dotnetcore/src/Project/Models/Vm/ManagedUserVM.cs.ejs
generators/server/templates/dotnetcore/src/Project/Service/Dto/PasswordChangeDto.cs.ejs
generators/server/templates/dotnetcore/src/Project/Service/Dto/UserDto.cs.ejs
generators/server/templates/dotnetcore/src/Project/Service/Mapper/UserMapper.cs.ejs
generators/server/templates/dotnetcore/src/Project/Service/Mapper/UserProfile.cs.ejs
generators/server/templates/dotnetcore/src/Project/Service/UserService.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Controllers/AccountControllerTest.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Controllers/AccountResourceIntTest.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Controllers/UserJwtControllerIntTest.cs.ejs
generators/server/templates/dotnetcore/test/Project.Test/Controllers/UserResourceIntTest.cs.ejs

Dto namespace refactoring and rename vm files/add DTO suffix to them.
Should be merged before the main dto PR

dto refactoring

---

generators/client/files-common.js
generators/languages/index.js

Fix Rtl support

---

generators/server/templates/dotnetcore/src/Project/Startup.cs.ejs

Fix swagger and indentation in startup.cs

---

generators/entity-server/templates/dotnetcore/src/Project/Service/Mapper/AutoMapperProfile.cs.ejs

Fix mapper generation with jhipster entity cli

---

generators/entity-server/templates/dotnetcore/src/Project/Controllers/EntityController.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Data/ApplicationDatabaseContext.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Models/Entity.cs.ejs
generators/entity-server/templates/dotnetcore/test/Project.Test/Controllers/EntityResourceIntTest.cs.ejs

Fix using with enums

---

generators/entity-client/index.js

Fix dto generation on client side

---

generators/entity-server/templates/dotnetcore/src/Project.Domain.Services/Service.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project.Domain/Entities/Entity.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project/Controllers/EntityController.cs.ejs

Fix relationship to User

---

generators/common/templates/dotnetcore/gitignore.ejs

Fix gitignore (Dockerfile)

---

generators/entity-server/templates/dotnetcore/src/Project.Domain.Services/Service.cs.ejs

Fix using in service

---

.gitignore
docs/Makefile
docs/conf.py
docs/getting-started.md
docs/index.rst
docs/make.bat

Added ReadTheDocs

---

package-lock.json
package.json

Updating outdated npm packages.

---

generators/server/templates/dotnetcore/src/Project/Configuration/AutoMapperStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Configuration/DatabaseStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Configuration/IdentityStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Configuration/NhipsterStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Configuration/ProblemDetailsStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Configuration/SecurityStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Configuration/ServiceStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Configuration/SwaggerStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Web/Extensions/HttpRequestExtensions.cs.ejs

replaced @this declarations in extension methods with appropriate variable names (fixes #383)

---

generators/common/files.js
generators/common/templates/dotnetcore/README.md.ejs
generators/common/templates/dotnetcore/editorconfig.ejs

Introduced editorconfig as part of the generated code.

---

generators/entity-client/files-blazor.js
generators/entity-client/templates/blazor/src/Project.Client/Models/Model.cs.ejs
generators/entity-client/templates/blazor/src/Project.Client/Pages/Entities/Entity/Entity.razor.ejs
generators/entity-client/templates/blazor/src/Project.Client/Pages/Entities/Entity/EntityDetail.razor.ejs
generators/entity-client/templates/blazor/src/Project.Client/Pages/Entities/Entity/EntityUpdate.razor.cs.ejs
generators/entity-client/templates/blazor/src/Project.Client/Pages/Entities/Entity/EntityUpdate.razor.ejs
generators/entity-client/templates/blazor/test/Project.Client.Test/Pages/Entities/Entity/EntityDetailTest.cs.ejs
generators/entity-client/templates/blazor/test/Project.Client.Test/Pages/Entities/Entity/EntityUpdateTest.cs.ejs
generators/entity/index.js

Blazor - one-to-one relationship generation 

---

generators/entity-server/files.js
generators/server/files.js
generators/server/index.js

Added gatling

---

generators/server/templates/dotnetcore/src/Project.Domain.Services/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project.Domain/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project.Dto/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project.Infrastructure/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs
generators/server/templates/dotnetcore/test/Project.Test/Project.Test.csproj.ejs

Updating multiple dependencies

---

generators/server/files.js
generators/server/templates/dotnetcore/src/Project.Dto/SwaggerResourceDto.cs.ejs
generators/server/templates/dotnetcore/src/Project/Configuration/SwaggerStartup.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/SwaggerController.cs.ejs

Add swagger-resources endpoint

---

generators/entity-server/templates/dotnetcore/src/Project.Infrastructure/Data/Extensions/DbContextExtensions.cs.ejs
generators/server/templates/dotnetcore/src/Project/Configuration/MvcStartup.cs.ejs

That was an easy fix for issue: #383

Renamed all @this variables.

---

.github/MAINTAINERS_REPLY_TEMPLATES/GUIDELINES_NOT_FOLLOWED.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/release-drafter.yml
CONTRIBUTING.md
README.md
generators/client/templates/blazor/src/Project.Client/Pages/Admin/UserManagement/UserDetail.razor.ejs
generators/client/templates/blazor/src/Project.Client/wwwroot/index.html.ejs
test-integration/scripts/01-init-env.sh

Replace master by main

---

generators/entity-server/templates/dotnetcore/src/Project.Infrastructure/Data/Repositories/EntityRepository.cs.ejs

Fix repository bug - issue #434

---

.github/workflows/test-integration-jwt.yml
.github/workflows/test-integration-microservice.yml
.github/workflows/test-integration-oauth.yml
generators/app/prompts.js
generators/client/templates/blazor/src/Project.Client/Project.Client.csproj.ejs
generators/client/templates/blazor/test/Project.Client.Test/Project.Client.Test.csproj.ejs
generators/common/templates/dotnetcore/src/Project/Dockerfile.ejs
generators/server/templates/dotnetcore/src/Project.Domain.Services/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project.Domain/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project.Infrastructure/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs
generators/server/templates/dotnetcore/test/Project.Test/Project.Test.csproj.ejs

Prepare migration to dotnet 5 release with dotnet RC 2 
related to #347

Migration to dotnet 5 rc2

---

test-integration/scripts/04-generate-entities-sample.sh

Update sonar-scanner version

---

generators/entity-server/files.js
generators/entity-server/templates/dotnetcore/src/Project.Dto/AuditedEntityBaseDto.cs.ejs
generators/entity-server/templates/dotnetcore/src/Project.Infrastructure/Data/ApplicationDatabaseContext.cs.ejs
generators/server/files.js
generators/server/templates/dotnetcore/src/Project.Domain/Entities/AuditedEntityBase.cs.ejs
generators/server/templates/dotnetcore/src/Project.Infrastructure/Data/ApplicationDatabaseContext.cs.ejs

Add entities audit support

---

generators/entity-server/templates/dotnetcore/src/Project/Controllers/EntityController.cs.ejs

Fix entity generation with service and without DTO

---

generators/server/templates/dotnetcore/src/Project/Web/Rest/Utilities/HeaderUtil.cs.ejs
generators/utils.js

Fix display Alert Notification in frontendApp

---

.github/workflows/test-integration-jwt.yml
.github/workflows/test-integration-microservice.yml
.github/workflows/test-integration-oauth.yml
generators/client/templates/blazor/src/Project.Client/Project.Client.csproj.ejs
generators/client/templates/blazor/test/Project.Client.Test/Project.Client.Test.csproj.ejs
generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs
generators/server/templates/dotnetcore/test/Project.Test/Project.Test.csproj.ejs

Update to dotnet 5

---

generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs

Fix issue #460 - Dotnet publish fails when using release configuration

---

generators/common/templates/dotnetcore/gitignore.ejs

Fix issue #461 - Git ignoring source files at ClientApp/src/app/admin/docs

---

docs/Features/database-migrations.md
generators/server/templates/dotnetcore/src/Project.Domain/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project.Infrastructure/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs

Fix Error when using migrations

---

test-integration/scripts/07-run-sonar-analyze.sh

Added sonar analyze on blazor

---

test-integration/scripts/01-init-env.sh
test-integration/scripts/07-run-sonar-analyze.sh

Fix sonar analyze on blazor 

---

.github/workflows/test-integration-jwt.yml
test-integration/scripts/05-run-generated-client-tests-of-sample.sh

Setup java 11 for sonar analysis

---

test-integration/scripts/04-generate-entities-sample.sh

Fix sonar key on project project

---

.release-it.json
package-lock.json
package.json

Added release-it package 

---

generators/entity-client/index.js

Fix npm spawn command on blazor client

---

generators/common/templates/dotnetcore/src/Project/Dockerfile.ejs

Fix env variables in dockerfile

---

generators/client/index.js
generators/common/templates/dotnetcore/src/Project/Dockerfile.ejs
generators/dotnet.js
test-integration/scripts/03-install-dependencies-app-sample.sh

Improve blazor installation experience

---

generators/client/templates/blazor/src/Project.Client/App.razor.cs.ejs
generators/client/templates/blazor/src/Project.Client/App.razor.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Account/Register.razor.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Admin/UserManagement/UserDetail.razor.cs.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Admin/UserManagement/UserDetail.razor.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Admin/UserManagement/UserManagement.razor.cs.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Admin/UserManagement/UserManagement.razor.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Admin/UserManagement/UserUpdate.razor.cs.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Admin/UserManagement/UserUpdate.razor.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Index.razor.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Login.razor.cs.ejs
generators/client/templates/blazor/src/Project.Client/Pages/Login.razor.ejs
generators/client/templates/blazor/src/Project.Client/Project.Client.csproj.ejs
generators/client/templates/blazor/src/Project.Client/Shared/Components/AlertError.razor.cs.ejs
generators/client/templates/blazor/src/Project.Client/Shared/Components/AlertError.razor.ejs
generators/client/templates/blazor/src/Project.Client/Shared/DeleteModal.razor.cs.ejs
generators/client/templates/blazor/src/Project.Client/Shared/DeleteModal.razor.ejs
generators/client/templates/blazor/src/Project.Client/Shared/MainLayout.razor.ejs
generators/client/templates/blazor/src/Project.Client/Shared/NavMenu.razor.ejs
generators/client/templates/blazor/test/Project.Client.Test/Pages/TestPages/TestAlertError.razor.ejs
generators/client/templates/blazor/test/Project.Client.Test/Project.Client.Test.csproj.ejs
generators/entity-client/templates/blazor/src/Project.Client/Pages/Entities/Entity/Entity.razor.ejs
generators/entity-client/templates/blazor/src/Project.Client/Pages/Entities/Entity/EntityDetail.razor.cs.ejs
generators/entity-client/templates/blazor/src/Project.Client/Pages/Entities/Entity/EntityDetail.razor.ejs
generators/entity-client/templates/blazor/src/Project.Client/Pages/Entities/Entity/EntityUpdate.razor.cs.ejs
generators/entity-client/templates/blazor/src/Project.Client/Pages/Entities/Entity/EntityUpdate.razor.ejs
generators/entity-client/templates/blazor/src/Project.Client/Shared/NavMenu.razor.ejs

[Blazor] - Allow to have a difference between app name and namespace

---

docs/Features/dependencies-management.md
docs/index.rst
generators/client/templates/blazor/src/Project.Client/Project.Client.csproj.ejs
generators/client/templates/blazor/test/Project.Client.Test/Project.Client.Test.csproj.ejs
generators/server/files.js
generators/server/index.js
generators/server/templates/dotnetcore/src/Directory.Build.targets
generators/server/templates/dotnetcore/src/Project.Domain.Services/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project.Domain/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project.Dto/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project.Infrastructure/Project.csproj.ejs
generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs
generators/server/templates/dotnetcore/test/Project.Test/Project.Test.csproj.ejs

fix #426 
@ivanmonteiro @maznag Can you review this ? 
It's big change for the project if i merge this all dependencies are managed by Directory.Build.targets

Added Directory.Build.targets file

---

generators/server/templates/dotnetcore/src/fakecsproj.csproj

Added fakecsproj for dependabot scan

---

generators/client/templates/blazor/test/Project.Client.Test/Project.Client.Test.csproj.ejs

[Blazor] - Added coverlet in blazor test project for sonar coverage

---

generators/common/templates/dotnetcore/README.md.ejs

merge PR #567 in main (@Pierre48)

Lowercase for Docker Tag (#567)

---

generators/server/templates/dotnetcore/src/Directory.Build.targets

Upgrade Entity Framework packages

---

generators/common/templates/dotnetcore/README.md.ejs

Update generated readme for blazor part

---

.github/workflows/generator.yml
.github/workflows/test-integration-jwt.yml
.github/workflows/test-integration-microservice.yml
.github/workflows/test-integration-oauth.yml

Related with https://github.com/jhipster/generator-jhipster/issues/14304

Update Nodejs version to 14.16.0

---

test-integration/scripts/00-install-all-jhipster.sh

Specify version for CI

---

generators/server/templates/dotnetcore/src/Project/Project.csproj.ejs

Fix sonar metrics

---

generators/client/templates/blazor/src/Project.Client/wwwroot/content/scss/vendor.scss.ejs
generators/client/templates/blazor/src/Project.Client/wwwroot/index.html.ejs
generators/entity-client/index.js
generators/entity/prompts.js

Rename webpack to webapp & Fix DTO

---

generators/server/templates/dotnetcore/src/Directory.Build.targets
generators/server/templates/dotnetcore/src/Project/Configuration/DatabaseStartup.cs.ejs

Fix compile error with Pomelo.EntityFrameworkCore.MySql v5.0.0

---

generators/server/templates/dotnetcore/src/Directory.Build.targets

Update Pomelo.EntityFrameworkCore.MySql to v5.0.1

---

generators/client/files-common.js
generators/common/files.js
generators/common/index.js

fix issue 929

---

generators/server/templates/dotnetcore/src/Project.Domain.Services/UserService.cs.ejs
generators/server/templates/dotnetcore/src/Project.Dto/UserDto.cs.ejs
generators/server/templates/dotnetcore/src/Project/Controllers/AccountController.cs.ejs
test-integration/scripts/09-verify-format.sh

Fix dotnet format

---

generators/entity-server/templates/dotnetcore/src/Project.Infrastructure/Data/Repositories/EntityRepository.cs.ejs
generators/server/templates/dotnetcore/src/Project.Domain.Services/UserService.cs.ejs
generators/server/templates/dotnetcore/src/Project.Domain/Repositories/Interfaces/IGenericRepository.cs.ejs
generators/server/templates/dotnetcore/src/Project.Domain/Repositories/Interfaces/IUnitOfWork.cs.ejs
generators/server/templates/dotnetcore/src/Project.Infrastructure/Data/Repositories/GenericRepository.cs.ejs
generators/server/templates/dotnetcore/src/Project.Infrastructure/Data/Repositories/UnitOfWork.cs.ejs

Many to many issue

---

.eslintrc.json
generators/server/templates/dotnetcore/src/Directory.Build.targets
package-lock.json
package.json

-   [X] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

Bump Dependencies

---

generators/server/templates/dotnetcore/src/Directory.Build.targets
package-lock.json
package.json

-   [X] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

Dependencies

---

.github/workflows/build-docker-image.yml
.github/workflows/generator.yml
.github/workflows/test-integration-jwt.yml
.github/workflows/test-integration-microservice.yml
.github/workflows/test-integration-oauth.yml

Improve github actions to not run twice with dependabot

---

generators/ci-cd/generator.mjs
generators/ci-cd/index.mjs

Create ci-cd submodule

---

generators/client/templates/blazor/src/Project.Client/wwwroot/index.html.ejs

[FIX] implemented suggested changes to fix login model view

---

generators/server/templates/dotnetcore/src/Project.Domain/Entities/AuditedEntityBase.cs.ejs

As discussed in issue #1137, I have changed the inheritance class of AuditedBaseEntity from IAuditedEntityBase to BaseEntity

AuditedBaseEntity now inherits from BaseEntity (#1137)

---

README.md

:memo: Remove running-local-blueprint-version-for-development part

---

generators/server/templates/dotnetcore/src/Directory.Packages.props

-   [X] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

Remove duplicated dependencies

---

generators/client/templates/blazor/test/Project.Client.Test/AlertErrorTest.cs.ejs
generators/client/templates/blazor/test/Project.Client.Test/Pages/Admin/UserManagement/UserDetailTest.cs.ejs
generators/entity-client/templates/blazor/test/Project.Client.Test/Pages/Entities/Entity/EntityDetailTest.cs.ejs
generators/entity-client/templates/blazor/test/Project.Client.Test/Pages/Entities/Entity/EntityTest.cs.ejs
generators/entity-client/templates/blazor/test/Project.Client.Test/Pages/Entities/Entity/EntityUpdateTest.cs.ejs
generators/server/templates/dotnetcore/src/Directory.Packages.props

Bump blazorise

---

generators/entity-server/templates/dotnetcore/test/Project.Test/Controllers/EntityControllerIntTest.cs.ejs
generators/server/templates/dotnetcore/src/Directory.Packages.props

-   [X] [All continuous integration tests](https://github.com/jhipster/generator-jhipster/actions) are green
-   [X] Tests are added where necessary
-   [X] Documentation is added/updated where necessary
-   [X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/generator-jhipster/blob/main/CONTRIBUTING.md) are followed

Bump fluent assertion

---

generators/server/templates/dotnetcore/src/Directory.Packages.props

Bump AutoMapper

---

generators/entity-server/templates/dotnetcore/src/Project.Domain/Entities/Entity.cs.ejs

Bugfix: remove UserId for one-to-one relationship

---

README.md
docs/Introduction/getting-started.md

:memo: remove link to jhispter and keep necessary command

---

generators/ci-cd/generator.mjs
generators/ci-cd/templates/.gitlab-ci.yml.ejs

Generate gitlab ci 

---

.github/workflows/test-integration-jwt.yml
.github/workflows/test-integration-microservice.yml
.github/workflows/test-integration-oauth.yml

:green_heart: update dotnet action to version 3

---

generators/app/index.js
generators/common/index.js

:construction: add js function to init git folder

---

.github/workflows/copyright-update.yml

Update copyright script

---

generators/app/index.js

remove cicd workflow from default workflow

---

cli/cli.cjs

fix cli with jhipster-dotnetcore folder

---

generators/bootstrap-dotnetcore/generator.js
package-lock.json

Upgrade to Jhipster v8

---

.github/workflows/build-docker-image.yml
Dockerfile

fix dockerfile

---

README.md
docs/Introduction/getting-started.md

Update documentation for jhipster v8

---

.github/workflows/test-integration-microservice.yml
.github/workflows/test-integration-oauth.yml

Fix node version

---

.vscode/launch.json
.vscode/tasks.json

[Jhipster-8] fix vs code debuuger

---

.gitattributes
.github/dependabot.yml
.readthedocs.yaml
.vscode/settings.json
generators/client/__snapshots__/generator.spec.js.snap
generators/common/__snapshots__/generator.spec.js.snap
generators/common/generator.js

[Jhipster 8] Some adjust (readthedocs/sonar/dependabot)

---

.gitignore
.yo-rc.json
package-lock.json
package.json
vitest.config.ts
vitest.test-setup.ts

Update generator-jhipster to 8.8.0

---

generators/dotnetcore/templates/dotnetcore/src/Directory.Packages.props

Fixes https://github.com/jhipster/jhipster-dotnetcore/pull/1535

bump components package

---

generators/dotnetcore/templates/dotnetcore/src/Directory.Packages.props
generators/dotnetcore/templates/dotnetcore/src/Project/appsettings.Development.json.ejs
generators/dotnetcore/templates/dotnetcore/src/Project/appsettings.Production.json.ejs
generators/dotnetcore/templates/dotnetcore/src/Project/appsettings.json.ejs

Update Db provider

---

generators/bootstrap-application/__snapshots__/generator.spec.js.snap
generators/bootstrap-application/generator.js

Fix jdl import with sqllite

---

.gitignore
package-lock.json
package.json

update generator-jhipster to 8.9.0

---

README.md

Updated the github actions badges on readme.md

---

.gitignore
.yo-rc.json
.yo-resolve
package-lock.json
package.json

update generator-jhipster to 8.10.0

---

docs/Features/email-config.md
docs/index.rst

docs: update email configuration section headers for consistency

---

.github/workflows/publish-sample-app.yml

feat: add GitHub Actions workflow for publishing sample app

---

README.md
generators/ci-cd/command.js
generators/ci-cd/generator.js

bugfix: ci-cd command failure

---

README.md

use Shields.io to show dependency status badge.
Close #1573

fix dependency status badge [skip ci]

---

.yo-rc.json
package-lock.json
package.json

Related to https://github.com/jhipster/generator-jhipster/issues/29424

update generator-jhipster to 8.11.0
